export * from "./NewPostIcon/NewPostIcon"
export * from "./DashboardIcon/DashboardIcon"
export * from "./FriendsIcon/FriendsIcon"
export * from "./ProfileIcon/ProfileIcon"
export * from "./SearchIcon/SearchIcon"